"""Reference scripted policy for robosuite Lift task.

Environment: Lift
Robot: Panda
Controller: OSC_POSE
Generated by: RoboScribe (hand-written reference)
"""

import numpy as np

# State machine states
APPROACH = 0
LOWER = 1
GRASP = 2
LIFT = 3
DONE = 4

state = APPROACH
grasp_counter = 0


def reset():
    """Reset state machine between episodes."""
    global state, grasp_counter
    state = APPROACH
    grasp_counter = 0


def get_action(obs):
    """Generate action to pick up the cube.

    Controller: OSC_POSE (7D) -> [dx, dy, dz, dax, day, daz, gripper]
    Gripper: -1 = open, 1 = close
    """
    global state, grasp_counter

    eef_pos = obs["robot0_eef_pos"]
    cube_pos = obs["cube_pos"]

    dx = cube_pos[0] - eef_pos[0]
    dy = cube_pos[1] - eef_pos[1]
    dz = cube_pos[2] - eef_pos[2]

    action = np.zeros(7)

    if state == APPROACH:
        # Move above the cube with gripper open
        action[0] = np.clip(dx * 10.0, -1, 1)
        action[1] = np.clip(dy * 10.0, -1, 1)
        action[2] = np.clip((cube_pos[2] + 0.05 - eef_pos[2]) * 10.0, -1, 1)
        action[6] = -1

        if abs(dx) < 0.01 and abs(dy) < 0.01 and abs(eef_pos[2] - cube_pos[2] - 0.05) < 0.01:
            state = LOWER

    elif state == LOWER:
        # Lower onto the cube
        action[0] = np.clip(dx * 10.0, -1, 1)
        action[1] = np.clip(dy * 10.0, -1, 1)
        action[2] = np.clip((cube_pos[2] - 0.01 - eef_pos[2]) * 10.0, -1, 1)
        action[6] = -1

        if eef_pos[2] - cube_pos[2] < 0.01:
            state = GRASP
            grasp_counter = 0

    elif state == GRASP:
        # Close gripper and wait
        action[0] = np.clip(dx * 5.0, -1, 1)
        action[1] = np.clip(dy * 5.0, -1, 1)
        action[2] = 0.0
        action[6] = 1

        grasp_counter += 1
        if grasp_counter > 20:
            state = LIFT

    elif state == LIFT:
        # Lift straight up
        action[2] = 1.0
        action[6] = 1

        if eef_pos[2] > 1.2:
            state = DONE

    elif state == DONE:
        action[6] = 1

    return action


if __name__ == "__main__":
    import robosuite as suite
    from robosuite.controllers import load_controller_config

    controller_config = load_controller_config(default_controller="OSC_POSE")
    env = suite.make(
        "Lift",
        robots="Panda",
        controller_configs=controller_config,
        has_renderer=True,
        has_offscreen_renderer=False,
        use_camera_obs=False,
        reward_shaping=True,
        horizon=200,
    )

    successes = 0
    num_episodes = 10

    for ep in range(num_episodes):
        obs = env.reset()
        reset()
        ep_reward = 0.0

        for step in range(200):
            action = get_action(obs)
            obs, reward, done, info = env.step(action)
            ep_reward += reward
            env.render()
            if done:
                break

        success = env._check_success()
        successes += 1 if success else 0
        print(f"Episode {ep}: reward={ep_reward:.2f}, success={success}")

    print(f"\nSuccess rate: {successes}/{num_episodes} = {successes/num_episodes:.0%}")
    env.close()
