"""Generated scripted policy for robosuite Lift task.

Task: lift the cube
Environment: Lift
Robot: Panda
Controller: OSC_POSE
Success rate: 100%
Attempts: 2
Generated by: RoboScribe v0.1.0
Date: 2026-03-11 02:48
"""


import numpy as np

# State machine states
APPROACH = 0
ALIGN = 1
LOWER = 2
GRASP = 3
WAIT_GRASP = 4
LIFT = 5
DONE = 6

state = APPROACH
grasp_counter = 0
lift_start_z = 0.0


def reset():
    """Reset state machine between episodes."""
    global state, grasp_counter, lift_start_z
    state = APPROACH
    grasp_counter = 0
    lift_start_z = 0.0


def get_action(obs):
    """Generate action to pick up the cube.

    Controller: OSC_POSE (7D) -> [dx, dy, dz, dax, day, daz, gripper]
    Gripper: -1 = open, 1 = close
    """
    global state, grasp_counter, lift_start_z

    eef_pos = obs["robot0_eef_pos"]
    cube_pos = obs["cube_pos"]

    # Compute position error
    dx = cube_pos[0] - eef_pos[0]
    dy = cube_pos[1] - eef_pos[1]
    dz = cube_pos[2] - eef_pos[2]

    action = np.zeros(7)

    if state == APPROACH:
        # Move above the cube with gripper open
        action[0] = dx * 10.0  # proportional control for x
        action[1] = dy * 10.0  # proportional control for y
        action[2] = (cube_pos[2] + 0.12 - eef_pos[2]) * 10.0  # higher hover
        action[6] = -1  # open gripper

        # Transition when well-aligned in x,y and above cube
        if abs(dx) < 0.008 and abs(dy) < 0.008 and (eef_pos[2] > cube_pos[2] + 0.10):
            state = ALIGN

    elif state == ALIGN:
        # Fine-tune alignment at high position before descending
        action[0] = dx * 15.0
        action[1] = dy * 15.0
        action[2] = 0.0  # hold height
        action[6] = -1  # keep gripper open

        # Transition when very well aligned
        if abs(dx) < 0.003 and abs(dy) < 0.003:
            state = LOWER

    elif state == LOWER:
        # Lower to grasp height (just above cube surface, lower than before)
        action[0] = dx * 10.0
        action[1] = dy * 10.0
        action[2] = (cube_pos[2] + 0.005 - eef_pos[2]) * 10.0  # very close to surface
        action[6] = -1  # keep gripper open

        # Transition when at target height
        if abs(eef_pos[2] - (cube_pos[2] + 0.005)) < 0.008:
            state = GRASP

    elif state == GRASP:
        # Close gripper fully
        action[0] = dx * 5.0  # maintain position
        action[1] = dy * 5.0
        action[2] = 0.0  # hold height
        action[6] = 1.0  # fully close gripper

        grasp_counter += 1
        if grasp_counter > 15:
            state = WAIT_GRASP
            grasp_counter = 0

    elif state == WAIT_GRASP:
        # Hold gripper closed and maintain position for stability
        action[0] = dx * 5.0
        action[1] = dy * 5.0
        action[2] = 0.0
        action[6] = 1.0  # keep gripper fully closed

        grasp_counter += 1
        if grasp_counter > 10:
            state = LIFT
            lift_start_z = eef_pos[2]

    elif state == LIFT:
        # Lift the cube above threshold (z > 0.85)
        action[0] = 0.0
        action[1] = 0.0
        action[2] = 0.3  # steady upward motion
        action[6] = 1.0  # keep gripper closed

        if eef_pos[2] > 0.85:
            state = DONE

    elif state == DONE:
        # Hold position at target height
        action[0] = 0.0
        action[1] = 0.0
        action[2] = 0.0
        action[6] = 1.0  # keep gripper closed

    # Clip actions to valid range
    action[:6] = np.clip(action[:6], -1.0, 1.0)
    return action


if __name__ == "__main__":
    import robosuite as suite
    from robosuite.controllers import load_controller_config

    controller_config = load_controller_config(default_controller="OSC_POSE")

    env = suite.make(
        "Lift",
        robots="Panda",
        controller_configs=controller_config,
        has_renderer=True,
        has_offscreen_renderer=False,
        use_camera_obs=False,
        reward_shaping=True,
        horizon=200,
    )

    successes = 0
    num_episodes = 10

    for ep in range(num_episodes):
        obs = env.reset()

        if "reset" in dir():
            reset()

        ep_reward = 0.0

        for step in range(200):
            action = get_action(obs)
            obs, reward, done, info = env.step(action)
            ep_reward += reward
            env.render()

            if done:
                break

        success = env._check_success()
        successes += 1 if success else 0

        print(f"Episode {ep}: reward={ep_reward:.2f}, success={success}")

    print(f"\nSuccess rate: {successes}/{num_episodes} = {successes/num_episodes:.0%}")

    env.close()
