"""Generated scripted policy for robosuite Stack task.

Task: stack cube A on cube B
Environment: Stack
Robot: Panda
Controller: OSC_POSE
Success rate: 100%
Attempts: 1
Generated by: RoboScribe v0.1.0
Date: 2026-03-11 19:14
"""


import numpy as np

# State machine states
APPROACH_A = 0
LOWER_A = 1
GRASP_A = 2
LIFT_A = 3
MOVE_TO_B = 4
LOWER_TO_B = 5
RELEASE = 6
RETREAT = 7
DONE = 8

state = APPROACH_A
counter = 0


def reset():
    """Reset state machine between episodes."""
    global state, counter
    state = APPROACH_A
    counter = 0


def get_action(obs):
    """Generate action to stack cubeA on cubeB.

    Controller: OSC_POSE (7D) -> [dx, dy, dz, dax, day, daz, gripper]
    Gripper: -1 = open, 1 = close
    """
    global state, counter

    eef_pos = obs["robot0_eef_pos"]
    cubeA_pos = obs["cubeA_pos"]
    cubeB_pos = obs["cubeB_pos"]

    action = np.zeros(7)

    if state == APPROACH_A:
        # Move above cubeA with safe height
        dx = cubeA_pos[0] - eef_pos[0]
        dy = cubeA_pos[1] - eef_pos[1]
        action[0] = dx * 10.0
        action[1] = dy * 10.0
        action[2] = (cubeA_pos[2] + 0.08 - eef_pos[2]) * 10.0
        action[6] = -1

        if abs(dx) < 0.01 and abs(dy) < 0.01 and abs(cubeA_pos[2] + 0.08 - eef_pos[2]) < 0.02:
            state = LOWER_A

    elif state == LOWER_A:
        # Lower to just above cubeA surface
        dx = cubeA_pos[0] - eef_pos[0]
        dy = cubeA_pos[1] - eef_pos[1]
        action[0] = dx * 10.0
        action[1] = dy * 10.0
        action[2] = (cubeA_pos[2] + 0.01 - eef_pos[2]) * 10.0
        action[6] = -1

        dz = cubeA_pos[2] + 0.01 - eef_pos[2]
        if abs(dz) < 0.02:
            state = GRASP_A
            counter = 0

    elif state == GRASP_A:
        # Hold position and close gripper
        dx = cubeA_pos[0] - eef_pos[0]
        dy = cubeA_pos[1] - eef_pos[1]
        action[0] = dx * 5.0
        action[1] = dy * 5.0
        action[2] = (cubeA_pos[2] + 0.01 - eef_pos[2]) * 5.0
        action[6] = 1

        counter += 1
        if counter > 15:
            state = LIFT_A

    elif state == LIFT_A:
        # Lift cubeA high enough to clear cubeB
        action[2] = 1.0
        action[6] = 1

        if eef_pos[2] > cubeB_pos[2] + 0.15:
            state = MOVE_TO_B

    elif state == MOVE_TO_B:
        # Move horizontally over cubeB while maintaining safe height
        dx = cubeB_pos[0] - eef_pos[0]
        dy = cubeB_pos[1] - eef_pos[1]
        action[0] = dx * 10.0
        action[1] = dy * 10.0
        action[2] = (cubeB_pos[2] + 0.15 - eef_pos[2]) * 5.0
        action[6] = 1

        if abs(dx) < 0.01 and abs(dy) < 0.01:
            state = LOWER_TO_B

    elif state == LOWER_TO_B:
        # Lower cubeA onto cubeB
        dx = cubeB_pos[0] - eef_pos[0]
        dy = cubeB_pos[1] - eef_pos[1]
        action[0] = dx * 10.0
        action[1] = dy * 10.0
        action[2] = (cubeB_pos[2] + 0.05 - eef_pos[2]) * 10.0
        action[6] = 1

        dz = cubeB_pos[2] + 0.05 - eef_pos[2]
        if abs(dz) < 0.02:
            state = RELEASE
            counter = 0

    elif state == RELEASE:
        # Open gripper to release cubeA
        action[6] = -1
        counter += 1
        if counter > 10:
            state = RETREAT

    elif state == RETREAT:
        # Move end-effector up to avoid collision
        action[2] = 1.0
        action[6] = -1
        if eef_pos[2] > 1.0:
            state = DONE

    elif state == DONE:
        # Final safe position
        action[6] = -1

    action[:6] = np.clip(action[:6], -1.0, 1.0)
    return action


if __name__ == "__main__":
    import robosuite as suite
    from robosuite.controllers import load_controller_config

    controller_config = load_controller_config(default_controller="OSC_POSE")

    env = suite.make(
        "Stack",
        robots="Panda",
        controller_configs=controller_config,
        has_renderer=True,
        has_offscreen_renderer=False,
        use_camera_obs=False,
        reward_shaping=True,
        horizon=200,
    )

    successes = 0
    num_episodes = 10

    for ep in range(num_episodes):
        obs = env.reset()

        if "reset" in dir():
            reset()

        ep_reward = 0.0

        for step in range(200):
            action = get_action(obs)
            obs, reward, done, info = env.step(action)
            ep_reward += reward
            env.render()

            if done:
                break

        success = env._check_success()
        successes += 1 if success else 0

        print(f"Episode {ep}: reward={ep_reward:.2f}, success={success}")

    print(f"\nSuccess rate: {successes}/{num_episodes} = {successes/num_episodes:.0%}")

    env.close()
