"""Generated scripted policy for robosuite Lift task.

Task: lift the cube

Environment: Lift
Robot: Panda
Controller: OSC_POSE
Success rate: 100%
Attempts: 3
Generated by: RoboScribe v0.1.0
Date: 2026-03-13 00:16
"""


import numpy as np

# State machine states
APPROACH = 0
LOWER = 1
GRASP = 2
LIFT = 3
DONE = 4

state = APPROACH
grasp_counter = 0


def reset():
    """Reset state machine between episodes."""
    global state, grasp_counter
    state = APPROACH
    grasp_counter = 0


def get_action(obs):
    """Generate action to pick up the cube.

    Controller: OSC_POSE (7D) -> [dx, dy, dz, dax, day, daz, gripper]
    Gripper: -1 = open, 1 = close
    """
    global state, grasp_counter

    eef_pos = np.atleast_1d(obs["robot0_eef_pos"])
    cube_pos = np.atleast_1d(obs["cube_pos"])
    gripper_qpos = np.atleast_1d(obs["robot0_gripper_qpos"])

    # Compute position error
    dx = cube_pos[0] - eef_pos[0]
    dy = cube_pos[1] - eef_pos[1]
    dz = cube_pos[2] - eef_pos[2]

    action = np.zeros(7)

    if state == APPROACH:
        # Move above the cube with gripper open
        action[0] = dx * 10.0
        action[1] = dy * 10.0
        action[2] = (cube_pos[2] + 0.12 - eef_pos[2]) * 10.0  # higher hover
        action[6] = -1  # open gripper

        # Transition when aligned in x,y and above
        if abs(dx) < 0.008 and abs(dy) < 0.008:
            state = LOWER

    elif state == LOWER:
        # Lower to just below cube top for grasp
        action[0] = dx * 10.0
        action[1] = dy * 10.0
        action[2] = (cube_pos[2] - 0.005 - eef_pos[2]) * 10.0  # grasp height
        action[6] = -1  # keep gripper open

        # Transition when close to target height
        if abs(eef_pos[2] - (cube_pos[2] - 0.005)) < 0.01:
            state = GRASP
            grasp_counter = 0

    elif state == GRASP:
        # Close gripper while holding position near cube center
        action[0] = dx * 5.0
        action[1] = dy * 5.0
        action[2] = (cube_pos[2] - 0.005 - eef_pos[2]) * 5.0  # hold z
        action[6] = 1.0  # full close

        grasp_counter += 1
        # Wait until gripper is nearly closed (sum of abs qpos > 0.035)
        if np.sum(np.abs(gripper_qpos)) > 0.035 and grasp_counter > 10:
            state = LIFT

    elif state == LIFT:
        # Lift upward steadily
        action[0] = 0.0
        action[1] = 0.0
        action[2] = 0.3  # lift
        action[6] = 1.0  # keep closed

        # Success condition: cube lifted above threshold (0.82 + 0.04 = 0.86)
        if cube_pos[2] > 0.86:
            state = DONE

    elif state == DONE:
        # Hold position
        action[0] = 0.0
        action[1] = 0.0
        action[2] = 0.0
        action[6] = 1.0

    # Clip actions to valid range
    action[:6] = np.clip(action[:6], -1.0, 1.0)
    return action


if __name__ == "__main__":
    import robosuite as suite
    from robosuite.controllers import load_controller_config

    controller_config = load_controller_config(default_controller="OSC_POSE")

    env = suite.make(
        "Lift",
        robots="Panda",
        controller_configs=controller_config,
        has_renderer=True,
        has_offscreen_renderer=False,
        use_camera_obs=False,
        reward_shaping=True,
        horizon=200,
    )

    successes = 0
    num_episodes = 10

    for ep in range(num_episodes):
        obs = env.reset()

        if "reset" in dir():
            reset()

        ep_reward = 0.0

        for step in range(200):
            action = get_action(obs)
            obs, reward, done, info = env.step(action)
            ep_reward += reward
            env.render()

            if done:
                break

        success = env._check_success()
        successes += 1 if success else 0

        print(f"Episode {ep}: reward={ep_reward:.2f}, success={success}")

    print(f"\nSuccess rate: {successes}/{num_episodes} = {successes/num_episodes:.0%}")

    env.close()
