"""Policy output writer — writes standalone policy files with metadata."""

from __future__ import annotations

import os
import textwrap
import re
from datetime import datetime

from roboscribe.config import Config


class PolicyWriter:
    """Writes generated policies as standalone Python files."""

    def __init__(self, config: Config):
        self.config = config

    def _clean_code(self, code: str) -> str:
        """Clean LLM-generated code to ensure valid Python."""

        code = code.strip()

        # Remove markdown code fences
        code = re.sub(r"^```python", "", code, flags=re.IGNORECASE).strip()
        code = re.sub(r"^```", "", code).strip()
        code = re.sub(r"```$", "", code).strip()

        # Normalize indentation
        code = textwrap.dedent(code)

        return code.strip()

    def write(
        self,
        code: str,
        env_name: str,
        task_description: str,
        success_rate: float,
        attempts: int,
        robot: str = "Panda",
    ) -> str:
        """Write policy code to a standalone .py file with metadata header."""

        filename = f"{env_name.lower()}_policy.py"
        output_path = os.path.join(self.config.output_dir, filename)

        # Clean the generated code
        code = self._clean_code(code)

        header = textwrap.dedent(f'''\
            """Generated scripted policy for robosuite {env_name} task.

            Task: {task_description}
            Environment: {env_name}
            Robot: {robot}
            Controller: OSC_POSE
            Success rate: {success_rate:.0%}
            Attempts: {attempts}
            Generated by: RoboScribe v0.1.0
            Date: {datetime.now().strftime("%Y-%m-%d %H:%M")}
            """
        ''')

        main_block = textwrap.dedent(f'''
            if __name__ == "__main__":
                import robosuite as suite
                from robosuite.controllers import load_controller_config

                controller_config = load_controller_config(default_controller="OSC_POSE")

                env = suite.make(
                    "{env_name}",
                    robots="{robot}",
                    controller_configs=controller_config,
                    has_renderer=True,
                    has_offscreen_renderer=False,
                    use_camera_obs=False,
                    reward_shaping=True,
                    horizon=200,
                )

                successes = 0
                num_episodes = 10

                for ep in range(num_episodes):
                    obs = env.reset()

                    if "reset" in dir():
                        reset()

                    ep_reward = 0.0

                    for step in range(200):
                        action = get_action(obs)
                        obs, reward, done, info = env.step(action)
                        ep_reward += reward
                        env.render()

                        if done:
                            break

                    success = env._check_success()
                    successes += 1 if success else 0

                    print(f"Episode {{ep}}: reward={{ep_reward:.2f}}, success={{success}}")

                print(f"\\nSuccess rate: {{successes}}/{{num_episodes}} = {{successes/num_episodes:.0%}}")

                env.close()
        ''')

        # Ensure code starts at column 0
        code = textwrap.dedent(code).lstrip()

        # Ensure header also starts at column 0
        header = textwrap.dedent(header).lstrip()

        full_content = header + "\n\n" + code

        if "if __name__" not in code:
            full_content += "\n\n" + main_block

        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

        with open(output_path, "w") as f:
            f.write(full_content)

        return output_path